export enum Routes {
  AuthPhone = 'AuthPhone',
  AuthCode = 'AuthCode',
  Policy = 'Policy',
  DeliveryAndPayment = 'DeliveryAndPayment',
  ProfileNotAuth = 'ProfileNotAuth',
  ProfileAuth = 'ProfileAuth',
  Profile = 'Profile',
  ProfileSettings = 'ProfileSettings',
  Catalog = 'Catalog',
  Cart = 'Cart',
  AddressCreate = 'AddressCreate',
  SelectCity = 'SelectCity',
  SelectOrganisationInMap = 'SelectOrganisationInMap',
  AddressList = 'AddressList',
  More = 'More',
  TabRootScreen = 'TabRootScreen',
  Payment = 'Payment',
  PaymentFinish = 'PaymentFinish',
}
